[package]
name = "overflow"
version = "0.1.0"
edition = "2021"

# check overflow-checks in main-repo Cargo.toml

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[profile.release]
overflow-checks = false
